# Labtask V

In [1]:
# 1. 
import torch
import numpy as np
import sys

ModuleNotFoundError: No module named 'torch'

In [12]:
# 2. 
def set_seed(seed: int) -> None:
    torch.manual_seed(seed)
    np.random.seed(seed)


In [13]:
# 3. 
set_seed(42)
arr = np.random.randint(0, 5, 6)
print(arr)
print(type(arr))

[3 4 2 4 4 1]
<class 'numpy.ndarray'>


In [14]:
# 4. 
x = torch.from_numpy(arr)
print(x)
print(x.type())

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)
torch.IntTensor


In [15]:
# 5. 
x = x.type(torch.int64)
print(x)
print(x.type())

tensor([3, 4, 2, 4, 4, 1])
torch.LongTensor


In [16]:
# 6. 
x = x.view(3, 2)
print(x)

tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [17]:
# 7. 
x[:,1]


tensor([4, 4, 1])

In [18]:
# 8. 
x_squared = x ** 2
print(x_squared)
print(x)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])
tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [19]:
# 9. 
y = torch.randint(0, 5, (2, 3))
print(y)

tensor([[2, 2, 1],
        [4, 1, 0]])


In [20]:
# 10. 
result = torch.mm(x, y)
print(result)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
